export const ADD_EXPENSE = 'add_exp'
export const ADD_EXPENSE_TYPE = 'add_exp_type'
export const EDIT_EXPENSE = 'edit_exp'
export const DELETE_EXPENSE = 'delete_exp'
export const DELETE_EXPENSE_TYPE = 'delete_exp_type'